apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dsi-api-core
  namespace: dsi-staging
spec:
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dsi-aws-ssm
  target:
    name: dsi-api-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - { secretKey: JWT_SECRET_KEY, remoteRef: { key: /dsi/staging/jwt-key } }
    - { secretKey: DATABASE_URL,   remoteRef: { key: /dsi/staging/db-url } }
    - { secretKey: REDIS_URL,      remoteRef: { key: /dsi/staging/redis-url } }
