"""
DSI Phase 5 Aerospace Coverage Expansion — 5 new specialist configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_5.
Generated: 2026-03-31 12:39 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

LaunchVehicleReliabilityAggregator = _simple_agg("launch_vehicle_reliability", "launch_vehicle_reliability_score")
SatelliteTechnologyMaturityAggregator = _simple_agg("satellite_technology_maturity", "satellite_technology_maturity_score")
OrbitalDebrisExposureAggregator = _simple_agg("orbital_debris_exposure", "orbital_debris_exposure_score")
InOrbitAnomalyHistoryAggregator = _simple_agg("in_orbit_anomaly_history", "in_orbit_anomaly_history_score")
GroundSegmentQualityAggregator = _simple_agg("ground_segment_quality", "ground_segment_quality_score")
MissionProfileAggregator = _categorical_agg("mission_profile", "mission_profile")
RotaryPilotExperienceAggregator = _simple_agg("rotary_pilot_experience", "rotary_pilot_experience_score")
RotaryMaintenanceQualityAggregator = _simple_agg("rotary_maintenance_quality", "rotary_maintenance_quality_score")
LandingZoneQualityAggregator = _simple_agg("landing_zone_quality", "landing_zone_quality_score")
PassengerLiabilityExposureAggregator = _simple_agg("passenger_liability_exposure", "passenger_liability_exposure_score")
UasOperationalScopeAggregator = _categorical_agg("uas_operational_scope", "uas_operational_scope")
UasRegulatoryComplianceAggregator = _simple_agg("uas_regulatory_compliance", "uas_regulatory_compliance_score")
AirspaceIntegrationAggregator = _simple_agg("airspace_integration", "airspace_integration_score")
UasPayloadRiskAggregator = _simple_agg("uas_payload_risk", "uas_payload_risk_score")
UasFleetReliabilityAggregator = _simple_agg("uas_fleet_reliability", "uas_fleet_reliability_score")
MroCertificationScopeAggregator = _simple_agg("mro_certification_scope", "mro_certification_scope_score")
WorkmanshipClaimsHistoryAggregator = _simple_agg("workmanship_claims_history", "workmanship_claims_history_score")
HangarkeepersExposureAggregator = _simple_agg("hangarkeepers_exposure", "hangarkeepers_exposure_score")
QualitySystemMaturityAggregator = _simple_agg("quality_system_maturity", "quality_system_maturity_score")
PartsTraceabilityAggregator = _simple_agg("parts_traceability", "parts_traceability_score")
