"""
DSI Phase 3 Marine Coverage Expansion — 5 new specialist configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_3.
Generated: 2026-03-31 12:38 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

CargoCommodityClassAggregator = _categorical_agg("cargo_commodity_class", "cargo_commodity_class")
PackagingQualityAggregator = _simple_agg("packaging_quality", "packaging_quality_score")
TransitModeAggregator = _categorical_agg("transit_mode", "transit_mode")
StorageExposureAggregator = _simple_agg("storage_exposure", "storage_exposure_score")
TheftPilferageExposureAggregator = _simple_agg("theft_pilferage_exposure", "theft_pilferage_exposure_score")
TemperatureControlAggregator = _simple_agg("temperature_control", "temperature_control_score")
TankerVettingStatusAggregator = _simple_agg("tanker_vetting_status", "tanker_vetting_status_score")
PollutionLiabilityExposureAggregator = _simple_agg("pollution_liability_exposure", "pollution_liability_exposure_score")
DoubleHullComplianceAggregator = _simple_agg("double_hull_compliance", "double_hull_compliance_score")
CargoCompatibilityAggregator = _simple_agg("cargo_compatibility", "cargo_compatibility_score")
StsOperationsAggregator = _simple_agg("sts_operations", "sts_operations_score")
UnitTypeAggregator = _categorical_agg("unit_type", "unit_type")
MooringIntegrityAggregator = _simple_agg("mooring_integrity", "mooring_integrity_score")
DpSystemReliabilityAggregator = _simple_agg("dp_system_reliability", "dp_system_reliability_score")
MetoceanExposureAggregator = _simple_agg("metocean_exposure", "metocean_exposure_score")
OffshoreClassComplianceAggregator = _simple_agg("offshore_class_compliance", "offshore_class_compliance_score")
PscDetentionRateAggregator = _simple_agg("psc_detention_rate", "psc_detention_rate_score")
IsmAuditQualityAggregator = _simple_agg("ism_audit_quality", "ism_audit_quality_score")
IspsComplianceAggregator = _simple_agg("isps_compliance", "isps_compliance_score")
SanctionsScreeningDepthAggregator = _simple_agg("sanctions_screening_depth", "sanctions_screening_depth_score")
ClassSurveyCurrencyAggregator = _simple_agg("class_survey_currency", "class_survey_currency_score")
