"""Recalibration proposals table (C-2).

Revision ID: 016
Revises: 015
Create Date: 2026-04-12

Stores RecalibrationProposal rows generated by the C-2 engine. Each row
is a complete proposal including signal report cards, weight changes,
tier threshold changes, impact assessment, and statistical evidence --
everything the governance UI (C-3) needs to review + approve + deploy.

Lifecycle:
    DRAFT -> PENDING_REVIEW -> APPROVED -> DEPLOYED
                           \-> REJECTED
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


revision: str = "016"
down_revision: str = "015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "recalibration_proposals",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("tenant_id", UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False),

        # Target
        sa.Column("coverage", sa.String(50), nullable=False),
        sa.Column("config_name", sa.String(100), nullable=False),

        # Provenance
        sa.Column("proposed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("proposed_by", sa.String(100), nullable=False),  # "system" or user_id
        sa.Column("trigger", sa.String(50), nullable=False, server_default="system"),  # system | manual | scheduled

        # Status (enum stored as string)
        sa.Column("status", sa.String(20), nullable=False, server_default="DRAFT"),

        # Analysis payload
        sa.Column("signal_report_cards", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("weight_changes", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("tier_threshold_changes", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("impact_assessment", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("statistical_evidence", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("sample_size", sa.Integer, nullable=False, server_default="0"),

        # Review fields (populated when status transitions to APPROVED/REJECTED)
        sa.Column("reviewer_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("review_decision", sa.String(20), nullable=True),
        sa.Column("review_rationale", sa.Text, nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),

        # Deployment (populated when status transitions to DEPLOYED)
        sa.Column("deployed_config_version_id", UUID(as_uuid=True), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=True),

        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_index("ix_recalibration_proposals_tenant_status", "recalibration_proposals", ["tenant_id", "status"])
    op.create_index("ix_recalibration_proposals_coverage", "recalibration_proposals", ["coverage", "config_name"])
    op.create_index("ix_recalibration_proposals_proposed_at", "recalibration_proposals", ["proposed_at"])


def downgrade() -> None:
    op.drop_index("ix_recalibration_proposals_proposed_at", table_name="recalibration_proposals")
    op.drop_index("ix_recalibration_proposals_coverage", table_name="recalibration_proposals")
    op.drop_index("ix_recalibration_proposals_tenant_status", table_name="recalibration_proposals")
    op.drop_table("recalibration_proposals")
