"""
DSI Phase 7 Financial Institutions Coverage Expansion — 4 new specialist configurations — Inference Functions

Auto-generated by CoverageExpansionGenerator from phase_7.
Generated: 2026-03-31 12:40 UTC
"""

import time

from signal_architecture.signals.inference.registry import register_inference_function
from signal_architecture.signals.types import SignalResult

from signal_architecture.signals.extractors.stubs.fi.phase_7_extractors import (
    CapitalAdequacyExtractor,
    LoanPortfolioQualityExtractor,
    RegulatoryExamResultsExtractor,
    BsaAmlComplianceExtractor,
    InterestRateSensitivityExtractor,
    RegulatoryLicensingStatusExtractor,
    CryptoAssetExposureExtractor,
    PlatformTechnologyRiskExtractor,
    ConsumerProtectionComplianceExtractor,
    PartnerBankDependencyExtractor,
)

from signal_architecture.signals.aggregators.implementations.fi.phase_7_aggregators import (
    CapitalAdequacyAggregator,
    LoanPortfolioQualityAggregator,
    RegulatoryExamResultsAggregator,
    BsaAmlComplianceAggregator,
    InterestRateSensitivityAggregator,
    RegulatoryLicensingStatusAggregator,
    CryptoAssetExposureAggregator,
    PlatformTechnologyRiskAggregator,
    ConsumerProtectionComplianceAggregator,
    PartnerBankDependencyAggregator,
)


async def _run_pipeline(signal_id, extractor, aggregator, entity_id, context,
                        score_field=None, default=50.0, **kwargs):
    """Standard extract → aggregate → return pipeline."""
    if score_field is None:
        score_field = f"{signal_id}_score"
    start = time.time()
    try:
        ext = await extractor.extract(entity_id, context)
        agg = await aggregator.aggregate([ext])
        score = round(float(agg.get("data", {}).get(score_field, default)), 1)
        return SignalResult(
            signal_id=signal_id,
            score=score,
            confidence=1.0,
            execution_time_ms=round((time.time() - start) * 1000, 1),
            raw_data=ext,
            aggregated_data=agg,
            metadata=kwargs,
        )
    except Exception:
        return SignalResult(
            signal_id=signal_id,
            score=default,
            confidence=0.3,
            execution_time_ms=round((time.time() - start) * 1000, 1),
        )


async def _run_categorical(signal_id, extractor, aggregator, entity_id, context,
                           cat_field=None, default="OTHER", **kwargs):
    """Standard extract → aggregate → return pipeline for categorical signals."""
    if cat_field is None:
        cat_field = signal_id
    start = time.time()
    try:
        ext = await extractor.extract(entity_id, context)
        agg = await aggregator.aggregate([ext])
        category = agg.get("data", {}).get(cat_field, default)
        return SignalResult(
            signal_id=signal_id,
            category=category,
            confidence=0.85,
            execution_time_ms=round((time.time() - start) * 1000, 1),
            raw_data=ext,
            aggregated_data=agg,
            metadata=kwargs,
        )
    except Exception:
        return SignalResult(
            signal_id=signal_id,
            category=default,
            confidence=0.0,
            execution_time_ms=round((time.time() - start) * 1000, 1),
        )


# =============================================================================
# REGISTERED INFERENCE FUNCTIONS
# =============================================================================

@register_inference_function("capital_adequacy_basefunction")
async def p7_01(entity_id, context):
    """Capital Adequacy Ratio"""
    return await _run_pipeline("capital_adequacy", CapitalAdequacyExtractor(), CapitalAdequacyAggregator(), entity_id, context)


@register_inference_function("loan_portfolio_quality_basefunction")
async def p7_02(entity_id, context):
    """Loan Portfolio Quality"""
    return await _run_pipeline("loan_portfolio_quality", LoanPortfolioQualityExtractor(), LoanPortfolioQualityAggregator(), entity_id, context)


@register_inference_function("regulatory_exam_results_basefunction")
async def p7_03(entity_id, context):
    """Regulatory Examination Results"""
    return await _run_pipeline("regulatory_exam_results", RegulatoryExamResultsExtractor(), RegulatoryExamResultsAggregator(), entity_id, context)


@register_inference_function("bsa_aml_compliance_basefunction")
async def p7_04(entity_id, context):
    """BSA/AML Compliance"""
    return await _run_pipeline("bsa_aml_compliance", BsaAmlComplianceExtractor(), BsaAmlComplianceAggregator(), entity_id, context)


@register_inference_function("interest_rate_sensitivity_basefunction")
async def p7_05(entity_id, context):
    """Interest Rate Sensitivity"""
    return await _run_pipeline("interest_rate_sensitivity", InterestRateSensitivityExtractor(), InterestRateSensitivityAggregator(), entity_id, context)


@register_inference_function("regulatory_licensing_status_basefunction")
async def p7_06(entity_id, context):
    """Regulatory Licensing Status"""
    return await _run_pipeline("regulatory_licensing_status", RegulatoryLicensingStatusExtractor(), RegulatoryLicensingStatusAggregator(), entity_id, context)


@register_inference_function("crypto_asset_exposure_basefunction")
async def p7_07(entity_id, context):
    """Crypto/Digital Asset Exposure"""
    return await _run_pipeline("crypto_asset_exposure", CryptoAssetExposureExtractor(), CryptoAssetExposureAggregator(), entity_id, context)


@register_inference_function("platform_technology_risk_basefunction")
async def p7_08(entity_id, context):
    """Platform Technology Risk"""
    return await _run_pipeline("platform_technology_risk", PlatformTechnologyRiskExtractor(), PlatformTechnologyRiskAggregator(), entity_id, context)


@register_inference_function("consumer_protection_compliance_basefunction")
async def p7_09(entity_id, context):
    """Consumer Protection Compliance"""
    return await _run_pipeline("consumer_protection_compliance", ConsumerProtectionComplianceExtractor(), ConsumerProtectionComplianceAggregator(), entity_id, context)


@register_inference_function("partner_bank_dependency_basefunction")
async def p7_10(entity_id, context):
    """Partner Bank / BaaS Dependency"""
    return await _run_pipeline("partner_bank_dependency", PartnerBankDependencyExtractor(), PartnerBankDependencyAggregator(), entity_id, context)

