"""
DSI Phase 7 Cyber Coverage Expansion — 9 new industry-specific configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_7.
Generated: 2026-03-29 11:39 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

ConnectedMedicalDeviceSecurityAggregator = _simple_agg("connected_medical_device_security", "connected_medical_device_security_score")
EhrSystemResilienceAggregator = _simple_agg("ehr_system_resilience", "ehr_system_resilience_score")
HipaaComplianceDepthAggregator = _simple_agg("hipaa_compliance_depth", "hipaa_compliance_depth_score")
ClinicalSystemSegmentationAggregator = _simple_agg("clinical_system_segmentation", "clinical_system_segmentation_score")
PhiDataVolumeAggregator = _simple_agg("phi_data_volume", "phi_data_volume_score")
HhsBreachPortalHistoryAggregator = _simple_agg("hhs_breach_portal_history", "hhs_breach_portal_history_score")
PaymentSystemArchitectureAggregator = _simple_agg("payment_system_architecture", "payment_system_architecture_score")
SwiftControlsAggregator = _simple_agg("swift_controls", "swift_controls_score")
PciComplianceDepthAggregator = _simple_agg("pci_compliance_depth", "pci_compliance_depth_score")
TransactionFraudControlsAggregator = _simple_agg("transaction_fraud_controls", "transaction_fraud_controls_score")
CoreBankingResilienceAggregator = _simple_agg("core_banking_resilience", "core_banking_resilience_score")
RegulatoryExaminationHistoryAggregator = _simple_agg("regulatory_examination_history", "regulatory_examination_history_score")
OtNetworkSegmentationAggregator = _simple_agg("ot_network_segmentation", "ot_network_segmentation_score")
ScadaSecurityPostureAggregator = _simple_agg("scada_security_posture", "scada_security_posture_score")
SafetyInstrumentedSystemAggregator = _simple_agg("safety_instrumented_system", "safety_instrumented_system_score")
OtPatchingCadenceAggregator = _simple_agg("ot_patching_cadence", "ot_patching_cadence_score")
NercCipComplianceAggregator = _simple_agg("nerc_cip_compliance", "nerc_cip_compliance_score")
SecureSdlcMaturityAggregator = _simple_agg("secure_sdlc_maturity", "secure_sdlc_maturity_score")
SbomCoverageAggregator = _simple_agg("sbom_coverage", "sbom_coverage_score")
TenantIsolationStrengthAggregator = _simple_agg("tenant_isolation_strength", "tenant_isolation_strength_score")
DependencyVulnerabilityExposureAggregator = _simple_agg("dependency_vulnerability_exposure", "dependency_vulnerability_exposure_score")
ApiSecurityPostureAggregator = _simple_agg("api_security_posture", "api_security_posture_score")
IncidentNotificationCapabilityAggregator = _simple_agg("incident_notification_capability", "incident_notification_capability_score")
UserAuthenticationStrengthAggregator = _simple_agg("user_authentication_strength", "user_authentication_strength_score")
DataRetentionPracticesAggregator = _simple_agg("data_retention_practices", "data_retention_practices_score")
CredentialBreachMonitoringAggregator = _simple_agg("credential_breach_monitoring", "credential_breach_monitoring_score")
ContentModerationCapabilityAggregator = _simple_agg("content_moderation_capability", "content_moderation_capability_score")
UserDataEncryptionAggregator = _simple_agg("user_data_encryption", "user_data_encryption_score")
ThirdPartyDataSharingAggregator = _simple_agg("third_party_data_sharing", "third_party_data_sharing_score")
ProductionOtSegmentationAggregator = _simple_agg("production_ot_segmentation", "production_ot_segmentation_score")
ProductionRecoveryCapabilityAggregator = _simple_agg("production_recovery_capability", "production_recovery_capability_score")
IpProtectionControlsAggregator = _simple_agg("ip_protection_controls", "ip_protection_controls_score")
SupplyChainDigitalRiskAggregator = _simple_agg("supply_chain_digital_risk", "supply_chain_digital_risk_score")
RansomwarePreparednessAggregator = _simple_agg("ransomware_preparedness", "ransomware_preparedness_score")
PointToPointEncryptionAggregator = _simple_agg("point_to_point_encryption", "point_to_point_encryption_score")
EcommerceSecurityPostureAggregator = _simple_agg("ecommerce_security_posture", "ecommerce_security_posture_score")
StoreNetworkIsolationAggregator = _simple_agg("store_network_isolation", "store_network_isolation_score")
LoyaltyDataProtectionAggregator = _simple_agg("loyalty_data_protection", "loyalty_data_protection_score")
PciAssessmentStatusAggregator = _simple_agg("pci_assessment_status", "pci_assessment_status_score")
AccessProvisioningAutomationAggregator = _simple_agg("access_provisioning_automation", "access_provisioning_automation_score")
EssentialServicesContinuityAggregator = _simple_agg("essential_services_continuity", "essential_services_continuity_score")
LegacySystemExposureAggregator = _simple_agg("legacy_system_exposure", "legacy_system_exposure_score")
MsIsacParticipationAggregator = _simple_agg("ms_isac_participation", "ms_isac_participation_score")
CitizenDataVolumeAggregator = _simple_agg("citizen_data_volume", "citizen_data_volume_score")
RansomwarePaymentGovernanceAggregator = _simple_agg("ransomware_payment_governance", "ransomware_payment_governance_score")
CyberIncidentResponseMaturityAggregator = _simple_agg("cyber_incident_response_maturity", "cyber_incident_response_maturity_score")
ClientDataClassificationAggregator = _simple_agg("client_data_classification", "client_data_classification_score")
EthicalWallCapabilityAggregator = _simple_agg("ethical_wall_capability", "ethical_wall_capability_score")
EmailSecurityPostureAggregator = _simple_agg("email_security_posture", "email_security_posture_score")
ClientDataEncryptionAtRestAggregator = _simple_agg("client_data_encryption_at_rest", "client_data_encryption_at_rest_score")
WireTransferControlsAggregator = _simple_agg("wire_transfer_controls", "wire_transfer_controls_score")
RemoteAccessSecurityAggregator = _simple_agg("remote_access_security", "remote_access_security_score")
