"""
DSI Phase 4 Commercial Casualty Coverage — 6 configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_4.
Generated: 2026-03-31 12:39 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

GlClassCodeAggregator = _categorical_agg("gl_class_code", "gl_class_code")
PremisesConditionAggregator = _simple_agg("premises_condition", "premises_condition_score")
ProductsCompletedOpsAggregator = _simple_agg("products_completed_ops", "products_completed_ops_score")
ContractualLiabilityAggregator = _simple_agg("contractual_liability", "contractual_liability_score")
SubcontractorManagementAggregator = _simple_agg("subcontractor_management", "subcontractor_management_score")
LitigationEnvironmentAggregator = _simple_agg("litigation_environment", "litigation_environment_score")
ExperienceModificationAggregator = _simple_agg("experience_modification", "experience_modification_score")
OshaComplianceAggregator = _simple_agg("osha_compliance", "osha_compliance_score")
SafetyProgrammeQualityAggregator = _simple_agg("safety_programme_quality", "safety_programme_quality_score")
ReturnToWorkProgrammeAggregator = _simple_agg("return_to_work_programme", "return_to_work_programme_score")
OccupationalDiseaseExposureAggregator = _simple_agg("occupational_disease_exposure", "occupational_disease_exposure_score")
FleetCompositionAggregator = _categorical_agg("fleet_composition", "fleet_composition")
DriverQualityAggregator = _simple_agg("driver_quality", "driver_quality_score")
TelematicsAdoptionAggregator = _simple_agg("telematics_adoption", "telematics_adoption_score")
RouteHazardAggregator = _simple_agg("route_hazard", "route_hazard_score")
AccidentFrequencyAggregator = _simple_agg("accident_frequency", "accident_frequency_score")
FleetMaintenanceAggregator = _simple_agg("fleet_maintenance", "fleet_maintenance_score")
PollutionConditionsAggregator = _simple_agg("pollution_conditions", "pollution_conditions_score")
UstAstComplianceAggregator = _simple_agg("ust_ast_compliance", "ust_ast_compliance_score")
RegulatoryEnforcementHistoryAggregator = _simple_agg("regulatory_enforcement_history", "regulatory_enforcement_history_score")
WasteManagementPracticesAggregator = _simple_agg("waste_management_practices", "waste_management_practices_score")
ThirdPartySiteExposureAggregator = _simple_agg("third_party_site_exposure", "third_party_site_exposure_score")
UnderlyingProgrammeQualityAggregator = _simple_agg("underlying_programme_quality", "underlying_programme_quality_score")
AttachmentPointAdequacyAggregator = _simple_agg("attachment_point_adequacy", "attachment_point_adequacy_score")
NuclearVerdictExposureAggregator = _simple_agg("nuclear_verdict_exposure", "nuclear_verdict_exposure_score")
TowerPositionAggregator = _simple_agg("tower_position", "tower_position_score")
PublicAccessVolumeAggregator = _simple_agg("public_access_volume", "public_access_volume_score")
SecurityMeasuresAggregator = _simple_agg("security_measures", "security_measures_score")
IncidentResponseCapabilityAggregator = _simple_agg("incident_response_capability", "incident_response_capability_score")
AlcoholServiceAggregator = _simple_agg("alcohol_service", "alcohol_service_score")
MultiLocationComplexityAggregator = _simple_agg("multi_location_complexity", "multi_location_complexity_score")
