"""
DSI Phase 6 D&O Coverage Expansion — 4 new specialist configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_6.
Generated: 2026-03-31 12:40 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

SecFilingQualityAggregator = _simple_agg("sec_filing_quality", "sec_filing_quality_score")
BoardIndependenceAggregator = _simple_agg("board_independence", "board_independence_score")
ShareholderActivismAggregator = _simple_agg("shareholder_activism", "shareholder_activism_score")
SecuritiesLitigationExposureAggregator = _simple_agg("securities_litigation_exposure", "securities_litigation_exposure_score")
ExecutiveCompensationStructureAggregator = _simple_agg("executive_compensation_structure", "executive_compensation_structure_score")
MaActivityAggregator = _simple_agg("ma_activity", "ma_activity_score")
IpoSpacExposureAggregator = _simple_agg("ipo_spac_exposure", "ipo_spac_exposure_score")
PeSponsorDynamicsAggregator = _simple_agg("pe_sponsor_dynamics", "pe_sponsor_dynamics_score")
BankruptcyDistressRiskAggregator = _simple_agg("bankruptcy_distress_risk", "bankruptcy_distress_risk_score")
RegulatoryInvestigationExposureAggregator = _simple_agg("regulatory_investigation_exposure", "regulatory_investigation_exposure_score")
