"""
DSI Phase 6 D&O Coverage Expansion — 4 new specialist configurations — Inference Functions

Auto-generated by CoverageExpansionGenerator from phase_6.
Generated: 2026-03-31 12:40 UTC
"""

import time

from signal_architecture.signals.inference.registry import register_inference_function
from signal_architecture.signals.types import SignalResult

from signal_architecture.signals.extractors.stubs.do.phase_6_extractors import (
    SecFilingQualityExtractor,
    BoardIndependenceExtractor,
    ShareholderActivismExtractor,
    SecuritiesLitigationExposureExtractor,
    ExecutiveCompensationStructureExtractor,
    MaActivityExtractor,
    IpoSpacExposureExtractor,
    PeSponsorDynamicsExtractor,
    BankruptcyDistressRiskExtractor,
    RegulatoryInvestigationExposureExtractor,
)

from signal_architecture.signals.aggregators.implementations.do.phase_6_aggregators import (
    SecFilingQualityAggregator,
    BoardIndependenceAggregator,
    ShareholderActivismAggregator,
    SecuritiesLitigationExposureAggregator,
    ExecutiveCompensationStructureAggregator,
    MaActivityAggregator,
    IpoSpacExposureAggregator,
    PeSponsorDynamicsAggregator,
    BankruptcyDistressRiskAggregator,
    RegulatoryInvestigationExposureAggregator,
)


async def _run_pipeline(signal_id, extractor, aggregator, entity_id, context,
                        score_field=None, default=50.0, **kwargs):
    """Standard extract → aggregate → return pipeline."""
    if score_field is None:
        score_field = f"{signal_id}_score"
    start = time.time()
    try:
        ext = await extractor.extract(entity_id, context)
        agg = await aggregator.aggregate([ext])
        score = round(float(agg.get("data", {}).get(score_field, default)), 1)
        return SignalResult(
            signal_id=signal_id,
            score=score,
            confidence=1.0,
            execution_time_ms=round((time.time() - start) * 1000, 1),
            raw_data=ext,
            aggregated_data=agg,
            metadata=kwargs,
        )
    except Exception:
        return SignalResult(
            signal_id=signal_id,
            score=default,
            confidence=0.3,
            execution_time_ms=round((time.time() - start) * 1000, 1),
        )


async def _run_categorical(signal_id, extractor, aggregator, entity_id, context,
                           cat_field=None, default="OTHER", **kwargs):
    """Standard extract → aggregate → return pipeline for categorical signals."""
    if cat_field is None:
        cat_field = signal_id
    start = time.time()
    try:
        ext = await extractor.extract(entity_id, context)
        agg = await aggregator.aggregate([ext])
        category = agg.get("data", {}).get(cat_field, default)
        return SignalResult(
            signal_id=signal_id,
            category=category,
            confidence=0.85,
            execution_time_ms=round((time.time() - start) * 1000, 1),
            raw_data=ext,
            aggregated_data=agg,
            metadata=kwargs,
        )
    except Exception:
        return SignalResult(
            signal_id=signal_id,
            category=default,
            confidence=0.0,
            execution_time_ms=round((time.time() - start) * 1000, 1),
        )


# =============================================================================
# REGISTERED INFERENCE FUNCTIONS
# =============================================================================

@register_inference_function("sec_filing_quality_basefunction")
async def p6_01(entity_id, context):
    """SEC Filing Quality"""
    return await _run_pipeline("sec_filing_quality", SecFilingQualityExtractor(), SecFilingQualityAggregator(), entity_id, context)


@register_inference_function("board_independence_basefunction")
async def p6_02(entity_id, context):
    """Board Independence & Composition"""
    return await _run_pipeline("board_independence", BoardIndependenceExtractor(), BoardIndependenceAggregator(), entity_id, context)


@register_inference_function("shareholder_activism_basefunction")
async def p6_03(entity_id, context):
    """Shareholder Activism Exposure"""
    return await _run_pipeline("shareholder_activism", ShareholderActivismExtractor(), ShareholderActivismAggregator(), entity_id, context)


@register_inference_function("securities_litigation_exposure_basefunction")
async def p6_04(entity_id, context):
    """Securities Litigation Exposure"""
    return await _run_pipeline("securities_litigation_exposure", SecuritiesLitigationExposureExtractor(), SecuritiesLitigationExposureAggregator(), entity_id, context)


@register_inference_function("executive_compensation_structure_basefunction")
async def p6_05(entity_id, context):
    """Executive Compensation Structure"""
    return await _run_pipeline("executive_compensation_structure", ExecutiveCompensationStructureExtractor(), ExecutiveCompensationStructureAggregator(), entity_id, context)


@register_inference_function("ma_activity_basefunction")
async def p6_06(entity_id, context):
    """M&A Transaction Activity"""
    return await _run_pipeline("ma_activity", MaActivityExtractor(), MaActivityAggregator(), entity_id, context)


@register_inference_function("ipo_spac_exposure_basefunction")
async def p6_07(entity_id, context):
    """IPO/SPAC Exposure"""
    return await _run_pipeline("ipo_spac_exposure", IpoSpacExposureExtractor(), IpoSpacExposureAggregator(), entity_id, context)


@register_inference_function("pe_sponsor_dynamics_basefunction")
async def p6_08(entity_id, context):
    """PE/VC Sponsor Dynamics"""
    return await _run_pipeline("pe_sponsor_dynamics", PeSponsorDynamicsExtractor(), PeSponsorDynamicsAggregator(), entity_id, context)


@register_inference_function("bankruptcy_distress_risk_basefunction")
async def p6_09(entity_id, context):
    """Bankruptcy & Financial Distress"""
    return await _run_pipeline("bankruptcy_distress_risk", BankruptcyDistressRiskExtractor(), BankruptcyDistressRiskAggregator(), entity_id, context)


@register_inference_function("regulatory_investigation_exposure_basefunction")
async def p6_10(entity_id, context):
    """Regulatory Investigation Exposure"""
    return await _run_pipeline("regulatory_investigation_exposure", RegulatoryInvestigationExposureExtractor(), RegulatoryInvestigationExposureAggregator(), entity_id, context)

