"""
DSI Phase 8 Financial & Political Risk Coverage — 5 configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_8.
Generated: 2026-03-31 12:41 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

BuyerCreditworthinessAggregator = _simple_agg("buyer_creditworthiness", "buyer_creditworthiness_score")
PaymentTermsExposureAggregator = _simple_agg("payment_terms_exposure", "payment_terms_exposure_score")
BuyerConcentrationAggregator = _simple_agg("buyer_concentration", "buyer_concentration_score")
CountryRiskExposureAggregator = _simple_agg("country_risk_exposure", "country_risk_exposure_score")
TradeDisputeFrequencyAggregator = _simple_agg("trade_dispute_frequency", "trade_dispute_frequency_score")
SectorCyclicalityAggregator = _simple_agg("sector_cyclicality", "sector_cyclicality_score")
SovereignRiskRatingAggregator = _categorical_agg("sovereign_risk_rating", "sovereign_risk_rating")
ExpropriationRiskAggregator = _simple_agg("expropriation_risk", "expropriation_risk_score")
CurrencyInconvertibilityAggregator = _simple_agg("currency_inconvertibility", "currency_inconvertibility_score")
ContractFrustrationAggregator = _simple_agg("contract_frustration", "contract_frustration_score")
PoliticalViolenceExposureAggregator = _simple_agg("political_violence_exposure", "political_violence_exposure_score")
PrincipalFinancialStrengthAggregator = _simple_agg("principal_financial_strength", "principal_financial_strength_score")
ProjectExecutionTrackRecordAggregator = _simple_agg("project_execution_track_record", "project_execution_track_record_score")
BacklogToCapacityAggregator = _simple_agg("backlog_to_capacity", "backlog_to_capacity_score")
BondDefaultHistoryAggregator = _simple_agg("bond_default_history", "bond_default_history_score")
ObligeeComplexityAggregator = _simple_agg("obligee_complexity", "obligee_complexity_score")
TravelExposureProfileAggregator = _simple_agg("travel_exposure_profile", "travel_exposure_profile_score")
CountryThreatLevelAggregator = _categorical_agg("country_threat_level", "country_threat_level")
ExecutiveProtectionAggregator = _simple_agg("executive_protection", "executive_protection_score")
CrisisResponseCapabilityAggregator = _simple_agg("crisis_response_capability", "crisis_response_capability_score")
ExpatriatePopulationAggregator = _simple_agg("expatriate_population", "expatriate_population_score")
