"""
DSI Phase 7 Financial Institutions Coverage Expansion — 4 new specialist configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_7.
Generated: 2026-03-31 12:40 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

CapitalAdequacyAggregator = _simple_agg("capital_adequacy", "capital_adequacy_score")
LoanPortfolioQualityAggregator = _simple_agg("loan_portfolio_quality", "loan_portfolio_quality_score")
RegulatoryExamResultsAggregator = _simple_agg("regulatory_exam_results", "regulatory_exam_results_score")
BsaAmlComplianceAggregator = _simple_agg("bsa_aml_compliance", "bsa_aml_compliance_score")
InterestRateSensitivityAggregator = _simple_agg("interest_rate_sensitivity", "interest_rate_sensitivity_score")
RegulatoryLicensingStatusAggregator = _simple_agg("regulatory_licensing_status", "regulatory_licensing_status_score")
CryptoAssetExposureAggregator = _simple_agg("crypto_asset_exposure", "crypto_asset_exposure_score")
PlatformTechnologyRiskAggregator = _simple_agg("platform_technology_risk", "platform_technology_risk_score")
ConsumerProtectionComplianceAggregator = _simple_agg("consumer_protection_compliance", "consumer_protection_compliance_score")
PartnerBankDependencyAggregator = _simple_agg("partner_bank_dependency", "partner_bank_dependency_score")
