"""
DSI Multi-Coverage Orchestration Types (Phase 10)

Data structures for multi-coverage and multi-locale pricing orchestration.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class LocaleDetectionMode(str, Enum):
    """How to detect applicable locales."""
    DISCOVERY = "discovery"  # Use website discovery TLD
    ALL = "all"  # Try all configured locales
    EXPLICIT = "explicit"  # Use provided list only


class ExecutionStatus(str, Enum):
    """Status of an individual run."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class MultiCoverageRequest:
    """
    Request for multi-coverage pricing.

    Enables pricing multiple coverages and/or locales
    from a single submission with shared signal caching.
    """
    entity_name: str
    domain_hint: Optional[str] = None

    # Coverage selection
    coverages: Optional[List[str]] = None  # None = auto-detect
    coverage_rules: Optional[Dict[str, Any]] = None  # Rules for auto-selection

    # Locale selection
    locales: Optional[List[str]] = None  # None = auto-detect from discovery
    locale_detection_mode: LocaleDetectionMode = LocaleDetectionMode.DISCOVERY

    # Cost control
    max_cost_units: Optional[int] = None  # Max signal calls
    require_approval_above: int = 50  # Prompt if exceeds

    # Execution options
    parallel: bool = True
    share_cache: bool = True  # Share signal cache across runs
    fail_fast: bool = False  # Stop on first failure

    # Submission data (optional traditional pricing inputs)
    submission_data: Dict[str, Any] = field(default_factory=dict)

    # Request metadata
    request_id: Optional[str] = None
    requested_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class PlannedRun:
    """
    A single planned coverage/locale combination.

    Represents one workflow execution in the multi-coverage plan.
    """
    coverage: str
    locale: str
    configuration: str
    estimated_signals: int
    estimated_cost: float
    priority: int = 0  # Higher = run first
    depends_on: Optional[List[str]] = None  # Run IDs this depends on

    # Runtime tracking
    run_id: Optional[str] = None
    status: ExecutionStatus = ExecutionStatus.PENDING

    def __post_init__(self):
        if self.run_id is None:
            self.run_id = f"{self.coverage}_{self.locale}"


@dataclass
class ExecutionPlan:
    """
    Complete plan for multi-coverage execution.

    Generated by the orchestrator before execution,
    can be reviewed/approved before running.
    """
    runs: List[PlannedRun]
    estimated_cost_units: int
    estimated_duration_seconds: float
    shared_signals: List[str]  # Signals that can be shared across runs
    requires_approval: bool

    # Plan metadata
    plan_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    approved: bool = False
    approved_by: Optional[str] = None

    @property
    def total_runs(self) -> int:
        """Total number of planned runs."""
        return len(self.runs)

    @property
    def coverages(self) -> List[str]:
        """Unique coverages in the plan."""
        return list(set(r.coverage for r in self.runs))

    @property
    def locales(self) -> List[str]:
        """Unique locales in the plan."""
        return list(set(r.locale for r in self.runs))


@dataclass
class CoverageResult:
    """
    Result for a single coverage/locale run.

    Wraps the WorkflowResult with additional orchestration context.
    """
    coverage: str
    locale: str
    configuration: str

    # Result data
    workflow_result: Optional[Any] = None  # WorkflowResult
    error: Optional[str] = None

    # Execution metrics
    status: ExecutionStatus = ExecutionStatus.PENDING
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_seconds: float = 0.0

    # Signal metrics
    signals_executed: int = 0
    signals_from_cache: int = 0
    cost_units: float = 0.0

    @property
    def success(self) -> bool:
        """Whether this run completed successfully."""
        return self.status == ExecutionStatus.COMPLETED and self.error is None

    @property
    def cache_hit_rate(self) -> float:
        """Percentage of signals from cache."""
        total = self.signals_executed + self.signals_from_cache
        if total == 0:
            return 0.0
        return self.signals_from_cache / total


@dataclass
class PackageDiscount:
    """
    Discount for bundling multiple coverages.
    """
    coverages: List[str]  # Required coverages for discount
    discount_rate: float  # e.g., 0.05 for 5%
    name: Optional[str] = None
    description: Optional[str] = None

    def applies_to(self, selected_coverages: List[str]) -> bool:
        """Check if discount applies to the selected coverages."""
        return all(c in selected_coverages for c in self.coverages)


@dataclass
class PackageRecommendation:
    """
    Recommendation for coverage package.
    """
    coverages: List[str]
    combined_premium: float
    discount_applied: float
    discount_rate: float
    savings: float
    reason: str


@dataclass
class MultiCoverageResult:
    """
    Combined results from multi-coverage pricing.

    Aggregates all coverage/locale runs with cross-coverage
    analysis and package recommendations.
    """
    entity_name: str
    discovered_domain: Optional[str] = None
    detected_locale: Optional[str] = None

    # Per-coverage/locale results
    coverage_results: Dict[str, CoverageResult] = field(default_factory=dict)

    # Best matches (if multiple locales tried per coverage)
    best_locale_per_coverage: Dict[str, str] = field(default_factory=dict)

    # Package analysis
    recommended_package: List[str] = field(default_factory=list)
    package_discount: float = 0.0
    package_recommendations: List[PackageRecommendation] = field(default_factory=list)

    # Aggregate premiums
    individual_premiums: Dict[str, float] = field(default_factory=dict)
    combined_premium: float = 0.0
    total_savings: float = 0.0

    # Aggregate metrics
    total_cost_units: float = 0.0
    total_duration_seconds: float = 0.0
    cache_hit_rate: float = 0.0

    # Execution summary
    total_runs: int = 0
    successful_runs: int = 0
    failed_runs: int = 0

    # Metadata
    result_id: Optional[str] = None
    completed_at: datetime = field(default_factory=datetime.utcnow)

    @property
    def success(self) -> bool:
        """Whether all runs completed successfully."""
        return self.failed_runs == 0 and self.successful_runs > 0

    @property
    def partial_success(self) -> bool:
        """Whether some runs succeeded."""
        return self.successful_runs > 0

    def get_result(self, coverage: str, locale: Optional[str] = None) -> Optional[CoverageResult]:
        """Get result for a specific coverage/locale."""
        if locale:
            key = f"{coverage}_{locale}"
            return self.coverage_results.get(key)

        # Return best locale result for coverage
        best_locale = self.best_locale_per_coverage.get(coverage)
        if best_locale:
            return self.coverage_results.get(f"{coverage}_{best_locale}")

        # Return first matching coverage
        for key, result in self.coverage_results.items():
            if result.coverage == coverage:
                return result
        return None


@dataclass
class CoverageDetectionRule:
    """
    Rule for auto-detecting applicable coverages.
    """
    coverage: str
    condition: str  # Python expression or simple check
    description: Optional[str] = None
    priority: int = 0


@dataclass
class OrchestrationConfig:
    """
    Configuration for multi-coverage orchestration.
    """
    # Coverage detection
    default_coverages: List[str] = field(default_factory=lambda: ["cyber"])
    coverage_detection_rules: List[CoverageDetectionRule] = field(default_factory=list)

    # Locale detection
    use_discovery_locale: bool = True
    fallback_locales: List[str] = field(default_factory=lambda: ["US", "UK"])

    # Cost control
    approval_threshold: int = 50
    max_parallel_runs: int = 10
    signal_cache_ttl: int = 3600  # seconds

    # Package discounts
    package_discounts: List[PackageDiscount] = field(default_factory=list)

    @classmethod
    def default(cls) -> "OrchestrationConfig":
        """Create default configuration."""
        return cls(
            default_coverages=["cyber"],
            fallback_locales=["US", "UK"],
            package_discounts=[
                PackageDiscount(
                    coverages=["fi", "do"],
                    discount_rate=0.05,
                    name="FI + D&O Bundle",
                ),
                PackageDiscount(
                    coverages=["fi", "do", "cyber"],
                    discount_rate=0.10,
                    name="Full Protection Package",
                ),
            ],
        )


@dataclass
class SharedSignalCache:
    """
    Shared signal cache across multi-coverage runs.

    Allows signal results to be reused across different
    coverage workflows for the same entity.
    """
    entity_id: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    ttl_seconds: int = 3600

    # Cached signals: signal_id -> result
    _cache: Dict[str, Any] = field(default_factory=dict)
    _hits: int = 0
    _misses: int = 0

    def get(self, signal_id: str) -> Optional[Any]:
        """Get cached signal result."""
        if signal_id in self._cache:
            self._hits += 1
            return self._cache[signal_id]
        self._misses += 1
        return None

    def set(self, signal_id: str, result: Any) -> None:
        """Cache signal result."""
        self._cache[signal_id] = result

    @property
    def hit_rate(self) -> float:
        """Cache hit rate."""
        total = self._hits + self._misses
        if total == 0:
            return 0.0
        return self._hits / total

    @property
    def size(self) -> int:
        """Number of cached signals."""
        return len(self._cache)
