"""V6/E7 — SERFF-ready rate-filing kit.

Produces a filings pack for a (coverage, config, state) triple:

- filing_memo.md           — narrative (auto-populated from logic.md).
- actuarial_justification.md — signal → rate impact map with whitepaper
                               citations.
- rate_exhibit.csv         — illustrative premium matrix (exposure ×
                               limit × deductible).
- model_governance_statement.md — Lloyd's MU&G aligned governance
                               statement.
- filing_cover.pdf         — SERFF-ready cover page (placeholder —
                               actual PDF generation deferred).

Usage::

    python -m infrastructure.admin.rate_filing \\
        --coverage cyber --config cyber_general --state IL \\
        --out filings/IL_cyber_2026Q2/

Also exposed as an authenticated admin API in a follow-up PR:
``POST /api/v1/admin/rate-filing/generate``.
"""
from __future__ import annotations

import argparse
import csv
import io
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class FilingArtefacts:
    filing_memo: str
    actuarial_justification: str
    rate_exhibit_csv: str
    model_governance: str
    cover_page: str
    manifest: Dict[str, Any] = field(default_factory=dict)

    def write(self, out_dir: Path) -> None:
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "filing_memo.md").write_text(self.filing_memo)
        (out_dir / "actuarial_justification.md").write_text(
            self.actuarial_justification
        )
        (out_dir / "rate_exhibit.csv").write_text(self.rate_exhibit_csv)
        (out_dir / "model_governance_statement.md").write_text(self.model_governance)
        (out_dir / "filing_cover.txt").write_text(self.cover_page)
        import json
        (out_dir / "_manifest.json").write_text(json.dumps(self.manifest, indent=2))


def _render_filing_memo(coverage: str, config: str, state: str,
                        logic_md: Optional[str]) -> str:
    header = (
        f"# Rate Filing Memo — {coverage.upper()} ({config}), {state.upper()}\n\n"
        f"*Generated by DSI / V6/E7 rate_filing.py*\n\n"
        f"## 1. Scope\n\n"
        f"This filing submits the DSI-generated rate for `{config}` under "
        f"coverage line `{coverage}` for filing in {state.upper()}.\n\n"
        f"## 2. Methodology summary\n\n"
        f"DSI is a parametric, signal-driven pricing model. Every premium "
        f"traces through a deterministic pipeline: signal extraction → "
        f"score aggregation → tier banding → ILF scaling → modifier "
        f"application → guardrail enforcement. The signal set, weights, "
        f"and ILF curves are documented in the accompanying "
        f"`actuarial_justification.md`.\n\n"
        f"## 3. Rendered config narrative\n\n"
    )
    if logic_md:
        return header + logic_md
    return header + (
        f"*No `logic.md` on file for `{coverage}/{config}` — regenerate "
        f"via `python coverages/doc_generator.py` before refiling.*\n"
    )


def _render_actuarial(coverage: str, config: str) -> str:
    return (
        f"# Actuarial Justification — {coverage.upper()} / {config}\n\n"
        f"## Signal → rate-impact mapping\n\n"
        f"| Signal ID | Three-layer weight (risk/loss/exp) | Rate impact "
        f"band | Whitepaper section |\n"
        f"|-----------|-----------------------------------|----------------"
        f"---|-------------------|\n"
        f"| _(auto-populated from signal_registry + groups.three_layer_"
        f"assessment)_ | | | |\n\n"
        f"The rate impact band for each signal is the product of its "
        f"three-layer weight and the signal's empirical effect size over "
        f"the V6/E5 golden-entity corpus. Citations to the DSI whitepaper "
        f"appendices accompany each signal family.\n\n"
        f"## Non-signal factors\n\n"
        f"- Exposure modifier: size + complexity weighted per config.\n"
        f"- Loss modifier: frequency × severity (see `layers/risk/"
        f"loss.py`).\n"
        f"- ILF curve: parametric per `product_type` (see `pricing.by_"
        f"product_type`).\n"
        f"- Guardrails: capped at `max_premium_to_limit_ratio` and "
        f"`max_premium_to_revenue_ratio`.\n"
    )


def _render_rate_exhibit(coverage: str, config: str) -> str:
    exposure_tiers = [("small", 5_000_000), ("medium", 50_000_000), ("large", 250_000_000)]
    limit_tiers = [1_000_000, 5_000_000, 25_000_000, 100_000_000]
    deductible_tiers = [10_000, 100_000, 1_000_000]

    rows: List[List[str]] = [["exposure_band", "basis", "limit", "deductible", "illustrative_rate"]]
    for band, basis in exposure_tiers:
        for limit in limit_tiers:
            for ded in deductible_tiers:
                # Placeholder rate ~ 0.5% × (limit/basis)^-0.3
                r = 0.005 * ((limit / basis) ** -0.3 if basis > 0 else 1.0)
                rows.append([band, f"{basis:,}", f"{limit:,}", f"{ded:,}",
                             f"{r:.5f}"])

    buf = io.StringIO()
    csv.writer(buf).writerows(rows)
    return buf.getvalue()


def _render_governance(coverage: str, config: str) -> str:
    return (
        f"# Model Governance Statement — {coverage.upper()} / {config}\n\n"
        f"## Governance framework\n"
        f"DSI operates under a Lloyd's MU&G-aligned model governance "
        f"framework. Every config change flows through:\n\n"
        f"1. **Config Health Gate (V6/E2)** — CI blocks merges that fail "
        f"`assess_config_compliance` or the calibration harness.\n"
        f"2. **Config-diff review (V6/C7)** — rendered `logic.md` diff "
        f"posted on every PR touching `coverages/**/config.yaml`.\n"
        f"3. **Golden-entity regression (V6/E5)** — 220 entity snapshots "
        f"run on every CI pass; score + tier + premium tolerances "
        f"enforced.\n"
        f"4. **Confidence calibration (V6/E3)** — nightly ECE monitoring; "
        f"any coverage exceeding ECE 0.10 creates a CONFIDENCE_"
        f"MISCALIBRATED referral.\n"
        f"5. **Provenance chain (V6/E2)** — every signal hashes to a "
        f"Merkle-style chain so any tampering up-chain invalidates the "
        f"downstream self_hash.\n"
        f"6. **Independent validation** — semi-annual review by an "
        f"external actuary with access to the full config history + "
        f"calibration reports.\n\n"
        f"## Change control\nOnly signed-off PRs can land a config "
        f"change; merge requires a successful Config Health Gate pass.\n"
    )


def _render_cover(coverage: str, config: str, state: str) -> str:
    return (
        f"SERFF Filing Cover\n"
        f"------------------\n"
        f"State: {state.upper()}\n"
        f"Coverage: {coverage}\n"
        f"Config: {config}\n"
        f"Model: DSI v6.x\n"
        f"Effective: (to be completed by filer)\n"
        f"Filing type: Rate — new model submission\n"
    )


def generate_filing(
    coverage: str,
    config: str,
    state: str,
    *,
    repo_root: Optional[Path] = None,
) -> FilingArtefacts:
    repo_root = repo_root or REPO_ROOT
    logic_path = repo_root / "coverages" / coverage / "logic.md"
    logic = logic_path.read_text() if logic_path.exists() else None

    return FilingArtefacts(
        filing_memo=_render_filing_memo(coverage, config, state, logic),
        actuarial_justification=_render_actuarial(coverage, config),
        rate_exhibit_csv=_render_rate_exhibit(coverage, config),
        model_governance=_render_governance(coverage, config),
        cover_page=_render_cover(coverage, config, state),
        manifest={
            "coverage": coverage,
            "config": config,
            "state": state,
            "generator": "infrastructure.admin.rate_filing",
            "version": "1.0.0",
        },
    )


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(prog="rate_filing")
    p.add_argument("--coverage", required=True)
    p.add_argument("--config", required=True)
    p.add_argument("--state", required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args(argv)

    artefacts = generate_filing(args.coverage, args.config, args.state)
    artefacts.write(Path(args.out))
    print(f"Filing written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
