"""
DSI Phase 2 Commercial Property Coverage — 5 configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_2.
Generated: 2026-03-31 12:35 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

ConstructionClassAggregator = _categorical_agg("construction_class", "construction_class")
BuildingAgeConditionAggregator = _simple_agg("building_age_condition", "building_age_condition_score")
BuildingCodeComplianceAggregator = _simple_agg("building_code_compliance", "building_code_compliance_score")
RoofConditionAggregator = _simple_agg("roof_condition", "roof_condition_score")
ElectricalSystemQualityAggregator = _simple_agg("electrical_system_quality", "electrical_system_quality_score")
RenovationHistoryAggregator = _simple_agg("renovation_history", "renovation_history_score")
OccupancyHazardGradeAggregator = _categorical_agg("occupancy_hazard_grade", "occupancy_hazard_grade")
TenantConcentrationAggregator = _simple_agg("tenant_concentration", "tenant_concentration_score")
ContentsValueDensityAggregator = _simple_agg("contents_value_density", "contents_value_density_score")
VacancyRateAggregator = _simple_agg("vacancy_rate", "vacancy_rate_score")
HousekeepingQualityAggregator = _simple_agg("housekeeping_quality", "housekeeping_quality_score")
WindZoneAggregator = _simple_agg("wind_zone", "wind_zone_score")
EarthquakeZoneAggregator = _simple_agg("earthquake_zone", "earthquake_zone_score")
FloodZoneAggregator = _simple_agg("flood_zone", "flood_zone_score")
WildfireZoneAggregator = _simple_agg("wildfire_zone", "wildfire_zone_score")
ConvectiveStormExposureAggregator = _simple_agg("convective_storm_exposure", "convective_storm_exposure_score")
GeographicConcentrationAggregator = _simple_agg("geographic_concentration", "geographic_concentration_score")
SprinklerCoverageAggregator = _categorical_agg("sprinkler_coverage", "sprinkler_coverage")
FireAlarmQualityAggregator = _simple_agg("fire_alarm_quality", "fire_alarm_quality_score")
FireDepartmentResponseAggregator = _simple_agg("fire_department_response", "fire_department_response_score")
FireSeparationAggregator = _simple_agg("fire_separation", "fire_separation_score")
WaterSupplyAdequacyAggregator = _simple_agg("water_supply_adequacy", "water_supply_adequacy_score")
RevenueConcentrationAggregator = _simple_agg("revenue_concentration", "revenue_concentration_score")
RecoveryTimeEstimateAggregator = _simple_agg("recovery_time_estimate", "recovery_time_estimate_score")
SupplyChainDependencyAggregator = _simple_agg("supply_chain_dependency", "supply_chain_dependency_score")
ContingentBiExposureAggregator = _simple_agg("contingent_bi_exposure", "contingent_bi_exposure_score")
BusinessContinuityPlanningAggregator = _simple_agg("business_continuity_planning", "business_continuity_planning_score")
