"""
DSI Infrastructure Models

Pydantic models for strongly-typed configuration handling.
"""

from .compiler import (
    ConfigCompilationError,
    ConfigNotFoundError,
    clear_config_cache,
    get_compiled_configs,
    get_config,
    get_coverage,
    list_configurations,
    list_coverages,
    migrate_dict_config,
    validate_all_configs,
)
from .config_schema import (
    # Enums
    ComparisonOperator,
    CorrelationDirection,
    ExpectationLevel,
    LimitConfigType,
    PricingMethod,
    ProxyTier,
    ScoreConditionAction,
    TierAction,
    # Core types
    CategoryFeature,
    CategoryGroup,
    ConfigMetadata,
    Coverage,
    CoverageConfig,
    DeductibleFactor,
    DimensionBlock,
    DirectQuery,
    Exposure,
    ExposureBand,
    ExposureDimension,
    ExposureDimensionConfig,
    Groups,
    ILFCurve,
    LimitConfiguration,
    LimitPackage,
    LossDimension,
    LossTierBand,
    LossTierBands,
    LossTierConstraints,
    MetadataBand,
    MetadataCategory,
    MinimumViableInputField,
    Pricing,
    ProductTypePricing,
    QueryCondition,
    RiskTierApplication,
    RiskTierBand,
    RiskTierBands,
    RiskTierInterpretation,
    RoutingConstraint,
    ScoreCondition,
    SignalCategories,
    SignalDefinition,
    ThreeLayerAssessment,
    ThreeLayerAssessmentGroup,
    TierBandRange,
)

__all__ = [
    # Compiler functions
    "ConfigCompilationError",
    "ConfigNotFoundError",
    "clear_config_cache",
    "get_compiled_configs",
    "get_config",
    "get_coverage",
    "list_configurations",
    "list_coverages",
    "migrate_dict_config",
    "validate_all_configs",
    # Enums
    "ComparisonOperator",
    "CorrelationDirection",
    "ExpectationLevel",
    "LimitConfigType",
    "PricingMethod",
    "ProxyTier",
    "ScoreConditionAction",
    "TierAction",
    # Core types
    "CategoryFeature",
    "CategoryGroup",
    "ConfigMetadata",
    "Coverage",
    "CoverageConfig",
    "DeductibleFactor",
    "DimensionBlock",
    "DirectQuery",
    "Exposure",
    "ExposureBand",
    "ExposureDimension",
    "ExposureDimensionConfig",
    "Groups",
    "ILFCurve",
    "LimitConfiguration",
    "LimitPackage",
    "LossDimension",
    "LossTierBand",
    "LossTierBands",
    "LossTierConstraints",
    "MetadataBand",
    "MetadataCategory",
    "MinimumViableInputField",
    "Pricing",
    "ProductTypePricing",
    "QueryCondition",
    "RiskTierApplication",
    "RiskTierBand",
    "RiskTierBands",
    "RiskTierInterpretation",
    "RoutingConstraint",
    "ScoreCondition",
    "SignalCategories",
    "SignalDefinition",
    "ThreeLayerAssessment",
    "ThreeLayerAssessmentGroup",
    "TierBandRange",
]
