"""
DSI Production Extractor - WAF (Web Application Firewall) Detection

Detects Web Application Firewall presence by analyzing HTTP response
headers, cookies, and behavior patterns.

This is a FREE extractor - uses HTTP requests only.

WAF Products Detected:
    - Cloudflare WAF
    - AWS WAF
    - Azure WAF / Front Door
    - Akamai Kona
    - Imperva/Incapsula
    - Sucuri
    - F5 BIG-IP ASM
    - Barracuda WAF
    - ModSecurity
    - Wordfence (WordPress)
    - Fortinet FortiWeb

Scoring Implications:
    - WAF present = Positive security signal
    - Enterprise WAF = Very positive
    - No WAF detected = May still have one (false negative possible)
"""

import logging
import re
from typing import Any, Dict, List, Optional

try:
    import requests
    REQUESTS_AVAILABLE = True
except ImportError:
    REQUESTS_AVAILABLE = False

from ..base import ProductionExtractor
from ....types import ExtractorResult

logger = logging.getLogger(__name__)


# WAF detection signatures
WAF_SIGNATURES = {
    'cloudflare': {
        'headers': {
            'cf-ray': r'.+',
            'cf-cache-status': r'.+',
            'server': r'^cloudflare$',
        },
        'cookies': ['__cfduid', '__cf_bm', 'cf_clearance'],
        'body_patterns': [r'cloudflare', r'cf-browser-verification'],
        'block_page_patterns': [r'Attention Required!.*Cloudflare', r'cf-error-'],
        'tier': 'enterprise',
    },
    'aws_waf': {
        'headers': {
            'x-amzn-requestid': r'.+',
            'x-amz-apigw-id': r'.+',
        },
        'cookies': ['awsalb', 'awsalbcors', 'AWSALB'],
        'body_patterns': [],
        'block_page_patterns': [r'Request blocked', r'AWS WAF'],
        'tier': 'enterprise',
    },
    'azure_waf': {
        'headers': {
            'x-azure-ref': r'.+',
            'x-ms-request-id': r'.+',
        },
        'cookies': [],
        'body_patterns': [],
        'block_page_patterns': [r'Azure.*blocked', r'Web Application Firewall'],
        'tier': 'enterprise',
    },
    'akamai': {
        'headers': {
            'x-akamai-transformed': r'.+',
            'akamai-grn': r'.+',
            'server': r'.*akamai.*',
        },
        'cookies': ['akamai_user_country', 'ak_bmsc', 'bm_sv', 'bm_sz'],
        'body_patterns': [],
        'block_page_patterns': [r'Access Denied.*Akamai', r'Reference.*#\d+\.\w+'],
        'tier': 'enterprise',
    },
    'imperva': {
        'headers': {
            'x-iinfo': r'.+',
            'x-cdn': r'.*incapsula.*',
        },
        'cookies': ['incap_ses_', 'visid_incap_', 'nlbi_'],
        'body_patterns': [r'incapsula', r'_Incapsula_Resource'],
        'block_page_patterns': [r'Request unsuccessful.*Incapsula', r'Incapsula incident ID'],
        'tier': 'enterprise',
    },
    'sucuri': {
        'headers': {
            'x-sucuri-id': r'.+',
            'x-sucuri-cache': r'.+',
            'server': r'.*sucuri.*',
        },
        'cookies': ['sucuri_cloudproxy_uuid'],
        'body_patterns': [r'sucuri'],
        'block_page_patterns': [r'Access Denied.*Sucuri', r'Sucuri WebSite Firewall'],
        'tier': 'standard',
    },
    'f5_bigip': {
        'headers': {
            'x-wa-info': r'.+',
            'server': r'.*bigip.*',
        },
        'cookies': ['BIGipServer', 'TS', 'F5_'],
        'body_patterns': [],
        'block_page_patterns': [r'Request Rejected', r'The requested URL was rejected'],
        'tier': 'enterprise',
    },
    'barracuda': {
        'headers': {
            'server': r'.*barracuda.*',
        },
        'cookies': ['barra_counter_session'],
        'body_patterns': [],
        'block_page_patterns': [r'Barracuda.*blocked', r'barracuda\.css'],
        'tier': 'enterprise',
    },
    'modsecurity': {
        'headers': {
            'server': r'.*mod_security.*|.*modsecurity.*',
        },
        'cookies': [],
        'body_patterns': [],
        'block_page_patterns': [
            r'ModSecurity',
            r'This error was generated by Mod_Security',
            r'Not Acceptable.*mod_security',
        ],
        'tier': 'open_source',
    },
    'wordfence': {
        'headers': {},
        'cookies': ['wfvt_', 'wordfence_verifiedHuman'],
        'body_patterns': [r'wordfence'],
        'block_page_patterns': [
            r'Wordfence.*blocked',
            r'Your access to this site has been limited',
            r'wordfence-ls-hd',
        ],
        'tier': 'standard',
    },
    'fortinet': {
        'headers': {
            'server': r'.*fortiweb.*',
        },
        'cookies': ['FORTIWAFSID'],
        'body_patterns': [],
        'block_page_patterns': [r'FortiWeb', r'Fortinet'],
        'tier': 'enterprise',
    },
    'reblaze': {
        'headers': {
            'server': r'.*reblaze.*',
            'x-rb-': r'.+',
        },
        'cookies': ['reblaze_session', 'rbzid'],
        'body_patterns': [r'reblaze'],
        'block_page_patterns': [r'reblaze'],
        'tier': 'enterprise',
    },
    'radware': {
        'headers': {
            'x-sl-compstate': r'.+',
        },
        'cookies': [],
        'body_patterns': [],
        'block_page_patterns': [r'Radware.*blocked', r'Protected by Radware'],
        'tier': 'enterprise',
    },
    'wallarm': {
        'headers': {
            'server': r'.*wallarm.*',
        },
        'cookies': [],
        'body_patterns': [],
        'block_page_patterns': [r'wallarm'],
        'tier': 'enterprise',
    },
}


class WAFPresenceExtractor(ProductionExtractor):
    """
    Detects WAF presence from HTTP response characteristics.

    Uses headers, cookies, and optionally response body analysis.

    Output:
        {
            'domain': str,
            'waf_detected': bool,
            'waf_products': [
                {
                    'name': str,
                    'tier': str,
                    'confidence': float,
                    'evidence': [...],
                }
            ],
            'primary_waf': str,
            'detection_methods_used': [...],
        }
    """

    SOURCE_NAME = "waf_presence"
    SOURCE_VERSION = "1.0"
    DEFAULT_TTL_SECONDS = 86400  # 24 hours
    RATE_LIMIT = 2.0
    COST_TIER = "free"

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        if not REQUESTS_AVAILABLE:
            raise ImportError(
                "requests is required for WAFPresenceExtractor. "
                "Install with: pip install requests"
            )
        super().__init__(config)
        self._timeout = config.get('timeout', 15) if config else 15
        self._check_body = config.get('check_body', False) if config else False
        self._test_block = config.get('test_block', False) if config else False

    def get_required_config(self) -> List[str]:
        return []

    def _do_extract(self, entity_id: str, **kwargs) -> ExtractorResult:
        """Detect WAF presence for a domain."""
        domain = entity_id.strip().lower()

        if not domain:
            return self._create_error_result("Empty domain provided")

        # Remove protocol if present
        if domain.startswith(('http://', 'https://')):
            domain = domain.split('://', 1)[1].split('/')[0]

        waf_detections = {}
        detection_methods = []

        # Normal request analysis
        try:
            normal_response = self._make_request(f"https://{domain}")
            if normal_response:
                detections = self._analyze_response(normal_response)
                for waf_name, evidence in detections.items():
                    if waf_name not in waf_detections:
                        waf_detections[waf_name] = {
                            'evidence': [],
                            'tier': WAF_SIGNATURES[waf_name]['tier'],
                        }
                    waf_detections[waf_name]['evidence'].extend(evidence)
                detection_methods.append('headers')
                detection_methods.append('cookies')

                if self._check_body and normal_response.text:
                    body_detections = self._analyze_body(normal_response.text)
                    for waf_name, evidence in body_detections.items():
                        if waf_name not in waf_detections:
                            waf_detections[waf_name] = {
                                'evidence': [],
                                'tier': WAF_SIGNATURES[waf_name]['tier'],
                            }
                        waf_detections[waf_name]['evidence'].extend(evidence)
                    detection_methods.append('body')
        except Exception as e:
            logger.debug(f"Normal request failed for {domain}: {e}")

        # Trigger-based detection (optional, sends suspicious-looking request)
        if self._test_block:
            try:
                block_response = self._make_block_test_request(f"https://{domain}")
                if block_response and block_response.status_code in [403, 406, 429]:
                    block_detections = self._analyze_block_page(block_response.text)
                    for waf_name, evidence in block_detections.items():
                        if waf_name not in waf_detections:
                            waf_detections[waf_name] = {
                                'evidence': [],
                                'tier': WAF_SIGNATURES[waf_name]['tier'],
                            }
                        waf_detections[waf_name]['evidence'].extend(evidence)
                    detection_methods.append('block_test')
            except Exception as e:
                logger.debug(f"Block test failed for {domain}: {e}")

        # Build results
        waf_products = []
        for waf_name, data in waf_detections.items():
            evidence_count = len(data['evidence'])
            confidence = min(0.95, 0.5 + (evidence_count * 0.15))
            waf_products.append({
                'name': waf_name,
                'tier': data['tier'],
                'confidence': round(confidence, 2),
                'evidence': data['evidence'][:5],  # Limit evidence
            })

        # Sort by confidence
        waf_products.sort(key=lambda x: x['confidence'], reverse=True)

        primary_waf = waf_products[0]['name'] if waf_products else None

        data = {
            'domain': domain,
            'waf_detected': len(waf_products) > 0,
            'waf_count': len(waf_products),
            'waf_products': waf_products,
            'primary_waf': primary_waf,
            'has_enterprise_waf': any(p['tier'] == 'enterprise' for p in waf_products),
            'detection_methods_used': list(set(detection_methods)),
        }

        confidence = 0.90 if waf_products else 0.60
        return self._create_success_result(data, confidence=confidence)

    def _make_request(self, url: str) -> Optional[requests.Response]:
        """Make a normal HTTP request."""
        try:
            return requests.get(
                url,
                timeout=self._timeout,
                allow_redirects=True,
                headers={
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    'Accept': 'text/html,application/xhtml+xml',
                },
            )
        except requests.exceptions.SSLError:
            # Try HTTP fallback
            try:
                return requests.get(
                    url.replace('https://', 'http://'),
                    timeout=self._timeout,
                    allow_redirects=True,
                    headers={
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    },
                )
            except:
                return None
        except:
            return None

    def _make_block_test_request(self, url: str) -> Optional[requests.Response]:
        """Make a request likely to trigger WAF block."""
        try:
            # Use a suspicious-looking but harmless path
            return requests.get(
                f"{url}/?test=<script>alert(1)</script>",
                timeout=self._timeout,
                allow_redirects=False,
                headers={
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                },
            )
        except:
            return None

    def _analyze_response(self, response: requests.Response) -> Dict[str, List[str]]:
        """Analyze response headers and cookies for WAF signatures."""
        detections = {}
        headers = {k.lower(): v for k, v in response.headers.items()}
        cookies = {c.name.lower(): c.value for c in response.cookies}

        for waf_name, signatures in WAF_SIGNATURES.items():
            evidence = []

            # Check headers
            for header_name, pattern in signatures.get('headers', {}).items():
                header_name_lower = header_name.lower()
                if header_name_lower in headers:
                    if re.search(pattern, headers[header_name_lower], re.IGNORECASE):
                        evidence.append(f"header:{header_name}={headers[header_name_lower][:50]}")

            # Check cookies
            for cookie_pattern in signatures.get('cookies', []):
                for cookie_name in cookies:
                    if cookie_pattern.lower() in cookie_name:
                        evidence.append(f"cookie:{cookie_name}")
                        break

            if evidence:
                detections[waf_name] = evidence

        return detections

    def _analyze_body(self, body: str) -> Dict[str, List[str]]:
        """Analyze response body for WAF signatures."""
        detections = {}
        body_lower = body.lower()

        for waf_name, signatures in WAF_SIGNATURES.items():
            evidence = []

            for pattern in signatures.get('body_patterns', []):
                if re.search(pattern, body_lower, re.IGNORECASE):
                    evidence.append(f"body_pattern:{pattern}")

            if evidence:
                detections[waf_name] = evidence

        return detections

    def _analyze_block_page(self, body: str) -> Dict[str, List[str]]:
        """Analyze a block page for WAF signatures."""
        detections = {}

        for waf_name, signatures in WAF_SIGNATURES.items():
            evidence = []

            for pattern in signatures.get('block_page_patterns', []):
                if re.search(pattern, body, re.IGNORECASE):
                    evidence.append(f"block_page:{pattern[:30]}")

            if evidence:
                detections[waf_name] = evidence

        return detections
