apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dsi-prod

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: dsi
  app.kubernetes.io/managed-by: kustomize

images:
  - name: dsi-api
    newTag: "0.2.0"
