"""
DSI Phase 6 Professional Indemnity Coverage Expansion — 11 new configurations — Aggregator Stubs

Auto-generated by CoverageExpansionGenerator from phase_6.
Generated: 2026-03-29 09:53 UTC
"""

from signal_architecture.signals.aggregators.base import ProductionAggregator


def _simple_agg(signal_id, score_key, default=50.0):
    """Factory: creates a score-passthrough aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = self._normalize_float(raw.get(score_key), default)
            return self._create_success_result({score_key: round(val, 1)}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _categorical_agg(signal_id, cat_key, default='OTHER'):
    """Factory: creates a categorical aggregator."""

    class Agg(ProductionAggregator):
        SOURCE_NAME = signal_id

        async def _do_aggregate(self, extractor_results):
            raw = self._get_primary_data(extractor_results, "data")
            val = raw.get(cat_key, default)
            return self._create_success_result({cat_key: val}, extractor_results)

    Agg.__name__ = Agg.__qualname__ = f'{_to_class(signal_id)}Aggregator'
    return Agg


def _to_class(signal_id):
    """Convert signal_id to PascalCase class name."""
    return ''.join(part.capitalize() for part in signal_id.split('_'))


# =============================================================================
# AGGREGATOR DEFINITIONS
# =============================================================================

LateralHireVolumeAggregator = _simple_agg("lateral_hire_volume", "lateral_hire_volume_score")
PriorActsCoverageAggregator = _simple_agg("prior_acts_coverage", "prior_acts_coverage_score")
ConflictSystemQualityAggregator = _simple_agg("conflict_system_quality", "conflict_system_quality_score")
TrustAccountComplianceAggregator = _simple_agg("trust_account_compliance", "trust_account_compliance_score")
ClassActionExposureAggregator = _simple_agg("class_action_exposure", "class_action_exposure_score")
PartnerDepartureRateAggregator = _simple_agg("partner_departure_rate", "partner_departure_rate_score")
MatterConcentrationAggregator = _simple_agg("matter_concentration", "matter_concentration_score")
CaseConcentrationAggregator = _simple_agg("case_concentration", "case_concentration_score")
ContingencyFeeRatioAggregator = _simple_agg("contingency_fee_ratio", "contingency_fee_ratio_score")
TrialSuccessRateAggregator = _simple_agg("trial_success_rate", "trial_success_rate_score")
StatuteTrackingComplianceAggregator = _simple_agg("statute_tracking_compliance", "statute_tracking_compliance_score")
CaseValueDistributionAggregator = _simple_agg("case_value_distribution", "case_value_distribution_score")
PcaobInspectionDeficiencyRateAggregator = _simple_agg("pcaob_inspection_deficiency_rate", "pcaob_inspection_deficiency_rate_score")
RestatementRateAggregator = _simple_agg("restatement_rate", "restatement_rate_score")
GoingConcernAccuracyAggregator = _simple_agg("going_concern_accuracy", "going_concern_accuracy_score")
SecEnforcementExposureAggregator = _simple_agg("sec_enforcement_exposure", "sec_enforcement_exposure_score")
AuditClientConcentrationAggregator = _simple_agg("audit_client_concentration", "audit_client_concentration_score")
AuditPartnerRotationComplianceAggregator = _simple_agg("audit_partner_rotation_compliance", "audit_partner_rotation_compliance_score")
SecuritiesLitigationExposureAggregator = _simple_agg("securities_litigation_exposure", "securities_litigation_exposure_score")
DesignDefectClaimsAggregator = _simple_agg("design_defect_claims", "design_defect_claims_score")
BuildingCodeComplianceAggregator = _simple_agg("building_code_compliance", "building_code_compliance_score")
ProjectComplexityScoreAggregator = _simple_agg("project_complexity_score", "project_complexity_score_score")
LatentDefectExposureAggregator = _simple_agg("latent_defect_exposure", "latent_defect_exposure_score")
SustainabilityCertificationAggregator = _simple_agg("sustainability_certification", "sustainability_certification_score")
PiConstructionPhaseAggregator = _categorical_agg("pi_construction_phase", "pi_construction_phase")
StructuralFailureHistoryAggregator = _simple_agg("structural_failure_history", "structural_failure_history_score")
PeLicenseComplianceAggregator = _simple_agg("pe_license_compliance", "pe_license_compliance_score")
GeotechnicalClaimFrequencyAggregator = _simple_agg("geotechnical_claim_frequency", "geotechnical_claim_frequency_score")
InfrastructureProjectExposureAggregator = _simple_agg("infrastructure_project_exposure", "infrastructure_project_exposure_score")
ProjectSizeConcentrationAggregator = _simple_agg("project_size_concentration", "project_size_concentration_score")
RemediationCostHistoryAggregator = _simple_agg("remediation_cost_history", "remediation_cost_history_score")
ProjectFailureRateAggregator = _simple_agg("project_failure_rate", "project_failure_rate_score")
SlaComplianceAggregator = _simple_agg("sla_compliance", "sla_compliance_score")
DataBreachExposureAggregator = _simple_agg("data_breach_exposure", "data_breach_exposure_score")
TechnologyStackCurrencyAggregator = _simple_agg("technology_stack_currency", "technology_stack_currency_score")
ImplementationMethodologyAggregator = _simple_agg("implementation_methodology", "implementation_methodology_score")
ClientDataEncryptionAggregator = _simple_agg("client_data_encryption", "client_data_encryption_score")
SuitabilityComplianceAggregator = _simple_agg("suitability_compliance", "suitability_compliance_score")
ComplaintPerAumAggregator = _simple_agg("complaint_per_aum", "complaint_per_aum_score")
RegulatoryExamResultsAggregator = _simple_agg("regulatory_exam_results", "regulatory_exam_results_score")
ChurningIndicatorsAggregator = _simple_agg("churning_indicators", "churning_indicators_score")
FeeTransparencyScoreAggregator = _simple_agg("fee_transparency_score", "fee_transparency_score_score")
ValuationAccuracyAggregator = _simple_agg("valuation_accuracy", "valuation_accuracy_score")
NegligentMisstatementHistoryAggregator = _simple_agg("negligent_misstatement_history", "negligent_misstatement_history_score")
PropertyTypeConcentrationAggregator = _simple_agg("property_type_concentration", "property_type_concentration_score")
MarketKnowledgeCurrencyAggregator = _simple_agg("market_knowledge_currency", "market_knowledge_currency_score")
RicsComplianceAggregator = _simple_agg("rics_compliance", "rics_compliance_score")
ContaminationAssessmentAccuracyAggregator = _simple_agg("contamination_assessment_accuracy", "contamination_assessment_accuracy_score")
RegulatoryComplianceTrackAggregator = _simple_agg("regulatory_compliance_track", "regulatory_compliance_track_score")
RemediationEffectivenessAggregator = _simple_agg("remediation_effectiveness", "remediation_effectiveness_score")
LongTailExposureAggregator = _simple_agg("long_tail_exposure", "long_tail_exposure_score")
CerclaSuperfundExposureAggregator = _simple_agg("cercla_superfund_exposure", "cercla_superfund_exposure_score")
TaxOpinionQualityAggregator = _simple_agg("tax_opinion_quality", "tax_opinion_quality_score")
IrsExaminationTrackAggregator = _simple_agg("irs_examination_track", "irs_examination_track_score")
EstatePlanningComplexityAggregator = _simple_agg("estate_planning_complexity", "estate_planning_complexity_score")
EngagementScopeClarityAggregator = _simple_agg("engagement_scope_clarity", "engagement_scope_clarity_score")
DeliverableAcceptanceRateAggregator = _simple_agg("deliverable_acceptance_rate", "deliverable_acceptance_rate_score")
ClientOutcomeCorrelationAggregator = _simple_agg("client_outcome_correlation", "client_outcome_correlation_score")
